### ISSUE TITLE
Calls ->file on a path object

### ISSUE THREAD

**Issue by autarch** [rjbs/Dist-Zilla-Plugin-PodWeaver#12]
->file called on a Dist::Zilla::Path object; this will cease to work in Dist::Zilla v7; downstream code should be updated to use Path::Tiny API, not Path::Class at /home/autarch/.perlbrew/libs/perl-5.22.1@dev/lib/perl5/Dist/Zilla/Plugin/PodWeaver.pm line 56.

**Comment by karenetheridge** [comment]
https://github.com/rjbs/Dist-Zilla-Plugin-PodWeaver/pull/11

**Comment by autarch** [comment]
Doh, should've checked first.
