### ISSUE TITLE
PodWeaver breaks __DATA__

### ISSUE THREAD

**Issue by van-de-bugger** [rjbs/Dist-Zilla-Plugin-PodWeaver#9]
Consider an example:

    $ cat dist.ini 
    name     = Assa
    version  = 0.001
    abstract = Assa
    [GenerateFile/lib/Assa.pm]
        filename = lib/Assa.pm
        content  = package Assa;
        content  = 1; # ©
        content  = __DATA__
        content  = ©
    ;~ [PodWeaver]

`dist.ini` is in UTF-8 encoding. Note two copyright `©` characters in the source. Now let us build the distro and check `lib/Assa.pm` file:

    $ dzil build
    [DZ] beginning to build Assa
    [DZ] writing Assa in Assa-0.001
    [DZ] building archive with Archive::Tar::Wrapper
    [DZ] writing archive to Assa-0.001.tar.gz
    [DZ] built in Assa-0.001

    $ cat Assa-0.001/lib/Assa.pm 
    package Assa;
    1; # ©
    __DATA__
    ©

Everything is ok, both copyright characters are in place. 

Now let's uncomment the `PodWeaver` plugin and repeat build:

    $ dzil build
    [DZ] beginning to build Assa
    [PodWeaver] [@Default/Name] couldn't find abstract in lib/Assa.pm
    [DZ] writing Assa in Assa-0.001
    [DZ] building archive with Archive::Tar::Wrapper
    [DZ] writing archive to Assa-0.001.tar.gz
    [DZ] built in Assa-0.001
    
    $ cat Assa-0.001/lib/Assa.pm 
    package Assa;
    1; # ©
    ...
    =cut

    __DATA__
    Â©

The copyright character in code is ok, but the same character in `__DATA__` section is preceded with `Â` character, which is not a part of original `lib/Assa.pm` file.

Looks like PodWeaver interprets UTF-8 data in `__DATA__` as ISO 8859-1 encoded text.

Dist::Zilla 5.039
Dist::Zilla::Plugin::PodWeaver 4.006
Pod::Weaver 4.012

**Comment by rjbs** [comment]
Could you provide a failing test case in a branch/PR please?

**Comment by van-de-bugger** [comment]
I have uploaded the test to gist: [t/data.t](https://gist.github.com/van-de-bugger/728bcccf6938e3154a02). I have tested it with current PodWeaver sources.

**Comment by perlancar** [comment]
Adding a note. I also have a dist (https://github.com/perlancar/perl-WordList-SU-LTIS ) that is pending release due to this issue. The Sundanese language uses an accented e (é). When the character is outside the DATA section, all is fine. But characters in the DATA section got mojibake'd.

Also tested with empty Pod::Weaver plugins, so it's probably DZP:PodWeaver or Pod::Weaver itself who does this instead of any of the weaver plugins.

**Comment by perlancar** [comment]
The problem is in Pod::Weaver::PerlMunger. `$end` is still bytes and needs to be decoded, just like `$perl`. PR added.

**Comment by karenetheridge** [comment]
...which is https://github.com/rjbs/Pod-Elemental-PerlMunger/pull/6

**Comment by rjbs** [comment]
This has been fixed upstream in Perlmunger.  Thanks!
